### ISSUE TITLE
This thing is brilliant!

### ISSUE THREAD

**Issue by AlexAndHisScripts** [Taonga07/chess#1]
Just read through the code, I'll run it in a minute. Is there anything I can help with? Also, you commented that you didn't know what a line is (line 106, chess.py) - it's calling the window manager to set the icon for your tkinter program. Put it in a try/except though, cause it's not cross platform and can error if you do it on a different one. You might also want to convert the guide you are writing into markdown so you can format stuff as code etc. 

Edit:
I'm not really sure what the following code does:
`                #FIXME Deobfuscate this...

                #changed to here - not debugged

                old_row_number, old_column_number = piecetomove

                if oldcolour != board[old_row_number][old_column_number].colour:

                    if board[old_row_number [old_column_number].checkMove(row_number,column_number):

                        board[row_number][column_number] = board[old_row_number][old_column_number]

                        board[piecetomove[0]][piecetomove[1]] = 0`

To my understanding, it takes the current column numbers of a piece, checks if the background is the board colour, and if it isn't, runs it against the check move function that isn't done yet, then does... something? ` board[row_number][column_number] = board[old_row_number][old_column_number]` and I'm not sure what `board[piecetomove[0]][piecetomove[1]] = 0` does either.

I'm not criticising you btw, my repositories are full of far, *far* worse code.

Edit 2: Just realised that you use a list for the board! For some reason I thought it was a class.

**Comment by Taonga07** [comment]
Thanks! Code club leader is helping me with the code. code line 106 was him checking what it meant but thanks any way. Did not know of cross platform vey interesting.

**Comment by Taonga07** [comment]
Code you pinpointed should ( when fixed )
Prevent a piece from taking another with the same colour. This I am still working on  though.
